config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "posts#index"

  resources :posts do
    resources :comments
  end
end

app/models/active_storage/attachment.rb
# frozen_string_literal: true

require "active_support/core_ext/module/delegation"

# Attachments associate records with blobs. Usually that's a one record-many blobs relationship,
# but it is possible to associate many different records with the same blob. A foreign-key constraint
# on the attachments table prevents blobs from being purged if they’re still attached to any records.
#
# Attachments also have access to all methods from ActiveStorage::Blob.
#
# If you wish to preload attachments or blobs, you can use these scopes:
#
#   # preloads attachments, their corresponding blobs, and variant records (if using `ActiveStorage.track_variants`)
#   User.all.with_attached_avatars
#
#   # preloads blobs and variant records (if using `ActiveStorage.track_variants`)
#   User.first.avatars.with_all_variant_records
class ActiveStorage::Attachment < ActiveStorage::Record
  self.table_name = "active_storage_attachments"

  belongs_to :record, polymorphic: true, touch: true
  belongs_to :blob, class_name: "ActiveStorage::Blob", autosave: true

  delegate_missing_to :blob
  delegate :signed_id, to: :blob

  after_create_commit :mirror_blob_later, :analyze_blob_later
  after_destroy_commit :purge_dependent_blob_later

  scope :with_all_variant_records, -> { includes(blob: :variant_records) }

  def self.ransackable_attributes(auth_object = nil)
    ["blob_id", "created_at", "id", "name", "record_id", "record_type"]
  end

  def

  # Synchronously deletes the attachment and {purges the blob}[rdoc-ref:ActiveStorage::Blob#purge].
  def purge
    transaction do
      delete
      record.touch if record&.persisted?
    end
    blob&.purge
  end

  # Deletes the attachment and {enqueues a background job}[rdoc-ref:ActiveStorage::Blob#purge_later] to purge the blob.
  def purge_later
    transaction do
      delete
      record.touch if record&.persisted?
    end
    blob&.purge_later
  end

  # Returns an ActiveStorage::Variant or ActiveStorage::VariantWithRecord
  # instance for the attachment with the set of +transformations+ provided.
  # See ActiveStorage::Blob::Representable#variant for more information.
  #
  # Raises an +ArgumentError+ if +transformations+ is a +Symbol+ which is an
  # unknown pre-defined variant of the attachment.
  def variant(transformations)
    case transformations
    when Symbol
      variant_name = transformations
      transformations = variants.fetch(variant_name) do
        record_model_name = record.to_model.model_name.name
        raise ArgumentError, "Cannot find variant :#{variant_name} for #{record_model_name}##{name}"
      end
    end

    blob.variant(transformations)
  end

  private
    def analyze_blob_later
      blob.analyze_later unless blob.analyzed?
    end

    def mirror_blob_later
      blob.mirror_later
    end

    def purge_dependent_blob_later
      blob&.purge_later if dependent == :purge_later
    end

    def dependent
      record.attachment_reflections[name]&.options&.fetch(:dependent, nil)
    end

    def variants
      record.attachment_reflections[name]&.variants
    end
end

ActiveSupport.run_load_hooks :active_storage_attachment, ActiveStorage::Attachment

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: {minimum: 1}

  belongs_to :post
  belongs_to :user
  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "post_id", "updated_at", "user_id"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true
  validates :description, presence: true, length: {maximum: 100}
  validates :title, presence: true, length: {maximum: 30}

  has_many :comments, dependent: :destroy
  has_one_attached :image
  def self.ransackable_attributes(auth_object = nil)
    ["author", "body", "created_at", "description", "id", "title", "updated_at", "user_id"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["comments", "image_attachment", "image_blob"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["comments", "posts"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to root_path, notice: 'Комментарий успешно создан'
    else
      redirect_to root_path, alert: 'Коментарий недопустим'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show update edit destroy]
  before_action :check_user, only: %i[update edit destroy]

  def index
    if params[:filter] == 'Все посты'
      @posts = Post.paginate(page: params[:page], per_page: 4)
    elsif params[:filter] == 'Мои посты'
      if current_user == nil
        redirect_to new_user_session_path, alert: 'Войдите в аккаунт для продолжения'
      else
        @posts = current_user.posts.paginate(page: params[:page], per_page: 4)
      end
    else
      @posts = Post.paginate(page: params[:page], per_page: 4)
    end
  end


  def new
    @post = Post.new
  end

  def create
    params[:post][:user_id] = current_user.id
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, notice: "Пост успешно создан"
    else
      redirect_to new_post_path, alert: "Неверные данные"
    end
  end

  def show
    @current_user = current_user
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path, notice: "Пост успешно обновлен"
    else
      redirect_to edit_post_path, alert: "Неверные данные"
    end
  end

  def destroy
    @post.destroy

    redirect_to root_path, notice: "Пост успешно удален"
  end

  private
  def post_params
    params.require(:post).permit(:title,:body, :description,:user_id, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_user
    if current_user.id != set_post.user_id
      redirect_to root_path, alert: "Это не ваш пост"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="wrapper">
  <% if flash[:notice].present? %>
    <p class="mt-sm mb-md message message-notice"><%=flash[:notice] %></p>
  <% elsif flash[:alert].present? %>
    <p class="mt-sm mb-md message message-alert"><%=flash[:alert] %></p>
  <% end %>
  <div class="navbar">
    <p class="title-lg "><%= link_to "Блог", root_path %></p>
    <div>
      <% if user_signed_in? %>
        <%= button_to "Профиль", edit_user_registration_path, method: :get, class: 'button title-sm mb-sm'%>
        <%= button_to "Выйти", destroy_user_session_path, method: :delete, class: 'button title-sm mb-mb' %>
      <% else %>
        <%= button_to "Войти", new_user_session_path, method: :get, class: "button title-sm mb-sm button-in" %>
        <%= button_to "Зарегистрироваться", new_user_registration_path,method: :get, class: "button title-sm mb-sm button-in" %>
      <%end %>
    </div>
  </div>
  <!--      <p class="notice"><%#= notice %></p>-->
  <!--      <p class="alert"><%#= alert %></p>-->
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.erb
<%= form_with model:post  do |form|%>
  <p class="mt-md"><%= form.label :title, 'Заголовок' %></p>
  <p><%= form.text_field :title, class: 'form-text-field' %></p>

  <p class="mt-sm"><%= form.label :description, 'Описание'%></p>
  <p><%= form.text_area :description,rows: 2, class: 'form-text-area' %></p>

  <p class="mt-sm"><%= form.label :body, 'Текст статьи'%></p>
  <p><%= form.text_area :body,rows: 5, class: 'form-text-area' %></p>

  <div class="mb-md">
    <%= form.file_field :image %>
  </div>

  <%= form.submit 'Сохранить', class: "button button-main"%>
<% end %>

app/views/posts/edit.html.erb
<div class ="container mt-lg">
  <h1 class="title-lg">Редактирование</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<%= form_tag(posts_path, method: "get") do %>
  <%= select_tag :filter, options_for_select(['Все посты', 'Мои посты']), prompt: 'Фильтр постов',onchange: "this.form.submit()" %>
<% end %>
<style> .filter-form { display: flex; align-items: flex-start; justify-content: flex-end}
select { margin-right: 10px;margin-top: 1rem }
select, input[type="submit"] { font-size: 16px; padding: 5px 10px; border-radius: 5px;}
input[type="submit"] { background-color: #5D9CEC; color: #fff; cursor: pointer; display: block; } </style>

<% @posts.each do |post| %>
  <div class="container mt-md">
    <%= link_to post.title, post,class: "text-blue title-md mt-sm mb-sm" %>
    <p class="mt-md"><%= post.description %></p>
  </div>
<% end %>
<br>
<%= link_to 'Создать статью', new_post_path, class: "button button-main"%>
<div class="mt-lg middle-sp">
  <%= will_paginate @posts%>
</div>

app/views/posts/new.html.erb
<div class="container mt-lg">
  <h1 class="title-lg">Создать пост</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container mt-lg">
  <h1 class="title-lg mt-md"><%= @post.title %></h1>
  <p class="image-show">
    <% if @post.image.attached? %>
      <%= image_tag(@post.image, class: "image-show", height: "100")%>
    <% end %>
  </p>
  <div>
    <p class="mt-md mb-md word-wrap"><%= @post.body%></p>

    <p class="post-footer"><%= "Автор: #{User.find(@post.user_id).email}" %></p>
    <p class="mb-lg"><%= @post.created_at.strftime(('%H:%M %d-%m-%Y')) %></p>
    <% if user_signed_in? && @current_user.id == @post.user_id%>
      <div class="mb-sm"><%= button_to "Изменить", edit_post_path(@post), method: :get, class: "button button-main" %></div>
      <div class="mb-md"><%= button_to "Удалить",  post_path(@post), method: :delete, class: "button button-main" %></div>
    <%end %>
    <div><%= button_to "Назад", :back, method: :get, class: "button button-main button-in mb-lg"%></div>
  </div>
</div>
<div class="container mt-lg">
  <h2 class="title-md">Комментарии</h2>
  <% @post.comments.each do |comment| %>
    <div class="container-pink mt-md">
      <p class="title-sm mb-md">
        <%= User.find(comment.user_id).email%>
      </p>
      <p>
        <%= comment.body %>
      </p>
    </div>
  <% end %>
</div>
<div class="container mt-lg">
  <h2 class="title-md mt-md">Добавить комментарий</h2>
  <%= form_with(model: [@post, @post.comments.build]) do |form| %>

    <p><%= form.label :body, 'Комментарий' %></p>
    <p> <%= form.text_area :body,rows: 5, class: 'form-text-area' %></p>

    <p class="mt-md"><%= form.submit 'Сохранить', class: "button button-main"%><p>
  <% end %>
</div>